apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {label-name}
  name: {label-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {label-name}
  template:
    metadata:
      labels:
        app: {label-name}
    spec:
      containers:
        - image: {image}
          imagePullPolicy: Always
          name: {label-name}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          env:
            - name: VOTING_API_SERVICE_HOST
              value: pipelines-vote-api
            - name: VOTING_API_SERVICE_PORT
              value: "9000"
