apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {label-name}
  name: {label-name}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {label-name}
    weight: 100
