apiVersion: v1
kind: Service
metadata:
  labels:
    app: {label-name}
  name: {label-name}
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {label-name}
